# Generated by Django 4.0.2 on 2022-02-13 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('faculty', models.CharField(max_length=35)),
                ('dept', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
